### ISSUE TITLE
请问相册中的缩略图 应该如何存放呢？

### ISSUE THREAD

**Issue by zengwangfa** [whyour/blog#4]
请问相册中的缩略图 应该如何存放呢？

**Comment by whyour** [comment]
> 请问相册中的缩略图 应该如何存放呢？

在 photos 和 min_photos 文件夹，其实存哪里都可以, 在 ins.js 中配置了图片路径
![image](https://user-images.githubusercontent.com/22700758/61343340-f5395900-a87f-11e9-88f2-b3ab64ed46f6.png)
你可以放在cdn中。

**Comment by yansheng836** [comment]
可以参考这个：[Hexo+Github实现相册功能 ](http://lawlite.me/2017/04/13/Hexo-Github%E5%AE%9E%E7%8E%B0%E7%9B%B8%E5%86%8C%E5%8A%9F%E8%83%BD/)

工作流程示意图：

[![mV0Yrj.jpg](https://s2.ax1x.com/2019/08/15/mV0Yrj.jpg)](https://imgchr.com/i/mV0Yrj)

**Comment by zengwangfa** [comment]
好的，谢谢！
